---
development:
  cloud_name: drkw6qcjz
  api_key: '138152763199323'
  api_secret: ZXnzhv7zB2NS2neEaxYQmtMUV9Y
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: drkw6qcjz
  api_key: '138152763199323'
  api_secret: ZXnzhv7zB2NS2neEaxYQmtMUV9Y
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: drkw6qcjz
  api_key: '138152763199323'
  api_secret: ZXnzhv7zB2NS2neEaxYQmtMUV9Y
  enhance_image_tag: true
  static_image_support: false
