require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Student::CourseUserTestsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Student::CourseUserTest. As you add validations to Student::CourseUserTest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Student::CourseUserTestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all student_course_user_tests as @student_course_user_tests" do
      course_user_test = Student::CourseUserTest.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:student_course_user_tests)).to eq([course_user_test])
    end
  end

  describe "GET #show" do
    it "assigns the requested student_course_user_test as @student_course_user_test" do
      course_user_test = Student::CourseUserTest.create! valid_attributes
      get :show, {:id => course_user_test.to_param}, valid_session
      expect(assigns(:student_course_user_test)).to eq(course_user_test)
    end
  end

  describe "GET #new" do
    it "assigns a new student_course_user_test as @student_course_user_test" do
      get :new, {}, valid_session
      expect(assigns(:student_course_user_test)).to be_a_new(Student::CourseUserTest)
    end
  end

  describe "GET #edit" do
    it "assigns the requested student_course_user_test as @student_course_user_test" do
      course_user_test = Student::CourseUserTest.create! valid_attributes
      get :edit, {:id => course_user_test.to_param}, valid_session
      expect(assigns(:student_course_user_test)).to eq(course_user_test)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Student::CourseUserTest" do
        expect {
          post :create, {:student_course_user_test => valid_attributes}, valid_session
        }.to change(Student::CourseUserTest, :count).by(1)
      end

      it "assigns a newly created student_course_user_test as @student_course_user_test" do
        post :create, {:student_course_user_test => valid_attributes}, valid_session
        expect(assigns(:student_course_user_test)).to be_a(Student::CourseUserTest)
        expect(assigns(:student_course_user_test)).to be_persisted
      end

      it "redirects to the created student_course_user_test" do
        post :create, {:student_course_user_test => valid_attributes}, valid_session
        expect(response).to redirect_to(Student::CourseUserTest.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved student_course_user_test as @student_course_user_test" do
        post :create, {:student_course_user_test => invalid_attributes}, valid_session
        expect(assigns(:student_course_user_test)).to be_a_new(Student::CourseUserTest)
      end

      it "re-renders the 'new' template" do
        post :create, {:student_course_user_test => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested student_course_user_test" do
        course_user_test = Student::CourseUserTest.create! valid_attributes
        put :update, {:id => course_user_test.to_param, :student_course_user_test => new_attributes}, valid_session
        course_user_test.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested student_course_user_test as @student_course_user_test" do
        course_user_test = Student::CourseUserTest.create! valid_attributes
        put :update, {:id => course_user_test.to_param, :student_course_user_test => valid_attributes}, valid_session
        expect(assigns(:student_course_user_test)).to eq(course_user_test)
      end

      it "redirects to the student_course_user_test" do
        course_user_test = Student::CourseUserTest.create! valid_attributes
        put :update, {:id => course_user_test.to_param, :student_course_user_test => valid_attributes}, valid_session
        expect(response).to redirect_to(course_user_test)
      end
    end

    context "with invalid params" do
      it "assigns the student_course_user_test as @student_course_user_test" do
        course_user_test = Student::CourseUserTest.create! valid_attributes
        put :update, {:id => course_user_test.to_param, :student_course_user_test => invalid_attributes}, valid_session
        expect(assigns(:student_course_user_test)).to eq(course_user_test)
      end

      it "re-renders the 'edit' template" do
        course_user_test = Student::CourseUserTest.create! valid_attributes
        put :update, {:id => course_user_test.to_param, :student_course_user_test => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested student_course_user_test" do
      course_user_test = Student::CourseUserTest.create! valid_attributes
      expect {
        delete :destroy, {:id => course_user_test.to_param}, valid_session
      }.to change(Student::CourseUserTest, :count).by(-1)
    end

    it "redirects to the student_course_user_tests list" do
      course_user_test = Student::CourseUserTest.create! valid_attributes
      delete :destroy, {:id => course_user_test.to_param}, valid_session
      expect(response).to redirect_to(student_course_user_tests_url)
    end
  end

end
